name: flutter_storage
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.1.0
  go_router: ^4.3.0
  json_annotation: ^4.6.0
  timeago: ^3.3.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true
